title: AMP Jekyll Theme
email: ""
description: > # this means to ignore newlines until "baseurl:"
  Documentation for amp-jekyll-theme
baseurl: "/amp-jekyll-theme" # the subpath of your site, e.g. /blog
url: "https://msroberts.github.io" # the base hostname & protocol for your site
github_username:  msroberts
permalink: pretty
paginate:	2 # The number of posts to show per page on your posts page
paginate_path: "/posts/page:num/"
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Build settings
markdown: kramdown

sass:
  style: compressed

gems:
  - jekyll-seo-tag
  - jekyll-paginate

# Theme customizations
amp:
  front_page_posts: 2
