title: AMP Jekyll Theme
email: ""
description: > # this means to ignore newlines until "baseurl:"
  Documentation for amp-jekyll-theme
baseurl: "/amp-jekyll-theme" # the subpath of your site, e.g. /blog
url: "https://msroberts.github.io" # the base hostname & protocol for your site
github_username:  msroberts

# Build settings
markdown: kramdown

sass:
  style: compressed;
