#!/bin/sh

set -e

script/build

amphtml-validator _site/index.html

if test -e "./_site/index.html";then
  echo "It builds!"
  rm -Rf _site
  exit 0
else
  echo "Huh. That's odd. The example site doesn't seem to build."
  exit 1
fi
